Fixes #23 pulldown-cmark unicode panic
euclio/aurelius pull request #24
Opened 2022-06-24 06:55 UTC by jasonm23

Unicode chars outside the En / standard set caused panic crash in earlier versions of `pulldown-cmark`

Fixes #23

2022-06-24 07:00 UTC, jasonm23 commented
@euclio just a quick mention that I'm doing a hard fork of Aurelius to use with Markdown-soma (an Emacs equivalent of vim-markdown-preview)

The rationale is incompatible modification the `.html` and `.js` static files for the features I'm adding for the Emacs version.

2022-06-24 16:59 UTC, euclio commented
What features are you adding? I'd prefer to find a way to incorporate them over forking.

2022-06-25 06:51 UTC, jasonm23 commented
On the preview html side I was thinking of adding user controlled throttling / debounce to help manage performance and lag.

I'd pass parameter(s) / value(s) from the `EDITOR` side as part of my hidden JSON header, as I did with `scrollTo`

This may be something you might be interested in too.  I didn't make a note about this here before but in my `markdown-soma` wrapper. I did away with the whole `json-rpc` thing and just feed the process `stdin`. It loops / re-renders on `EOF`.  I wanted to keep the process from having to know anything its data.

2022-06-25 06:58 UTC, jasonm23 commented
BTW, is anything that needs doing before merging this PR?  It's a pretty nasty bug for anyone who's not using straight ASCII.

2022-06-25 19:38 UTC, euclio commented
> scroll to the area you're editing.  I pass this in the HTML as a comment
with embedded JSON.  It's not working the way I would like, but getting a
1:1 positive match on browser and editor is an tough goal. (Impossible
probably)

This is something that I'd like to do as well, as long as it's configurable.

>  I depend on a different highlightsjs so that I have all the themes
available.

I just updated the highlight.js version in the latest release, this might not be necessary anymore?

> was trying to integrate mermaid, on hold for now

Once I finish the async refactor I plan to factor out the rendering into a trait, so you can implement any rendering you like.

> On the preview html side I was thinking of adding user controlled throttling / debounce to help manage performance and lag.

I'd like to add this as well, I have some client-side debouncing in the vim plugin but it would be better to add this upstream.

> BTW I didn't make a note about this here before but in my markdown-soma wrapper. I did away with the whole json-rpc thing and just feed the process stdin. It loops / re-renders on EOF. I wanted to keep the process from having to know anything about its data. For example I don't want to maintain any structure info or handling on that end, just let the EDITOR and the Browser client work it out between them.

I'm planning to make a language-server-protocol implementation of aurelius (maybe even part of this repository) to make things editor agnostic.

2022-06-25 19:38 UTC, euclio requested changes

2022-06-25 19:38 UTC, euclio commented on Cargo.toml
> +version = "0.7.5"
Please don't bump the version in this PR, I'll do that when I release it.

2022-06-26 00:04 UTC, jasonm23 commented
Re the bump sure I'll take that out.

Good news on the other feature ideas.

I'm not really sure what benefit the lsp service would be though?



On Sun, 26 June 2022, 02:39 Andy Russell, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In Cargo.toml
> <https://github.com/euclio/aurelius/pull/24#discussion_r906716959>:
>
> > @@ -1,6 +1,6 @@
>  [package]
>  name = "aurelius"
> -version = "0.7.4"
> +version = "0.7.5"
>
> Please don't bump the version in this PR, I'll do that when I release it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/euclio/aurelius/pull/24#pullrequestreview-1019347195>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAARPI267LTSCICNFYHKNWLVQ5N5TANCNFSM5ZWXV25A>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-06-26 23:09 UTC, merged